// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Projeto1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void projeto1() {
    // Test name: Projeto 1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://livros.inoveteste.com.br/");
    // 2 | setWindowSize | 1936x1056 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    // 3 | click | css=#sidr-navigation-container > #nav-wrap > #primary_menu > #menu-item-80 span | 
    driver.FindElement(By.CssSelector("#sidr-navigation-container > #nav-wrap > #primary_menu > #menu-item-80 span")).Click();
    // 4 | click | name=your-name | 
    driver.FindElement(By.Name("your-name")).Click();
    // 5 | type | name=your-name | Keven Henrique
    driver.FindElement(By.Name("your-name")).SendKeys("Keven Henrique");
    // 6 | type | name=your-email | kevenhenrique@outlook.com
    driver.FindElement(By.Name("your-email")).SendKeys("kevenhenrique@outlook.com");
    // 7 | type | name=your-subject | Saber mais sobre o valor?
    driver.FindElement(By.Name("your-subject")).SendKeys("Saber mais sobre o valor?");
    // 8 | type | name=your-message | Saber mais sobre valores ? 
    driver.FindElement(By.Name("your-message")).SendKeys("Saber mais sobre valores ? ");
    // 9 | click | css=.wpcf7-submit | 
    driver.FindElement(By.CssSelector(".wpcf7-submit")).Click();
    // 10 | verifyElementPresent | css=.wpcf7-response-output | 
    var elements = driver.FindElements(By.CssSelector(".wpcf7-response-output"));
    Assert.True(elements.Count > 0);
  }
}
